# use SIRC's managed LSF runner
default:
  tags: [lsf]
variables:
  SIRC_LSF_QUEUE: alg_isp_q
  # avoid issues with the docker registry login
  SIRC_USER: sircdevops
  # Build and deploy on dedicated host 
  DOCKER_HOST: "ssh://docker-prod-srv-1"

stages:
  - build
  - deploy

build:
  stage: build
  script:
    # not all LSF servers have up-to-date docker compose
    # so we are forced to use "-"
    - docker-compose build

deploy:
  stage: deploy
  when: manual
  # only:
  #   - master
  environment:
    name: production
    # url: https://emma_backend.transchip.com
  script:
    - docker-compose build
    - docker-compose push
    - docker-compose pull
    - docker-compose -f docker-compose.yml -f production.yaml up --force-recreate -d 
