version: '3.3'

services:
  coma_backend:
    image: <PLACEHOLDER_REGISTRY_HOST>/coma_server:backend
    build:
      cache_from: [<PLACEHOLDER_REGISTRY_HOST>/coma_server:backend]
      context: .
    environment:
      - HOME=/tmp
      - PORT=3000
    user: <PLACEHOLDER_UID>:<PLACEHOLDER_GID>
    ports:
      - 8484:3000